apiVersion: apps/v1
kind: Deployment
metadata:
  name: ikuber-nextjs-deployment
spec:
  replicas: 2  # Adjust the number of replicas based on your needs
  selector:
    matchLabels:
      app: ikuber-nextjs
  template:
    metadata:
      labels:
        app: ikuber-nextjs
    spec:
      containers:
      - name: ikuber-nextjs-container
        image: akhieshthakur/ikuber_nextjs:latest
        ports:
        - containerPort: 3000
