apiVersion: v1
kind: Service
metadata:
  name: ikuber-nextjs-service
spec:
  selector:
    app: ikuber-nextjs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
  